name: Benchmarks

# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  push:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Run Google C++ Benchmark Framework example
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang cmake
          version: 1.0      

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -D CMAKE_BUILD_TYPE=Release
          -D SANITIZE=OFF
          -D TEST=OFF
          -D BENCHMARK=ON

      - name: Build project
        run: cmake --build build --config Release
      
      - name: Run benchmark 
        run: ./build/Benchmarks --benchmark_format=json | tee benchmark_result.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
